### ISSUE TITLE
Publish UI bundle to some place

### ISSUE THREAD

**Issue by sebastian-sommerfeld-io** [sommerfeld-io-archive/website#45]
Publish UI bundle to some spot (possibly as an attachment to the Github Release) ... Otherwise I would not be able to use this in other projects (say an NHL Fantasy Game which should come with app-pages and static docs-pages combined in one UI) ... maybe as [NPM package to Docker Packages](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry#publishing-a-package).

### Todos
- [ ] Update `docs/modules/ROOT/pages/ui-bundle/about.adoc`
- [ ] Publish similar to DockerImages (`rc` from `main` branch and released versions)
- [ ] Document all supported artifact repositories (and why it won't be Artifactory) ... ADR?
