### ISSUE TITLE
Deploy to some local test environment

### ISSUE THREAD

**Issue by sebastian-sommerfeld-io** [sommerfeld-io-archive/website#56]
Only deploy `:rc` images. Deploy a complete compose-stack (a new compose config targeted for the test environment). Add a reverse proxy to this config, to expose on port 80.

### Tasks
- [ ] Install Raspi
- [ ] Provision Raspi with Ansible
- [ ] https://github.com/sebastian-sommerfeld-io/configs/issues/135
- [ ] Document in
    - [ ] `docs/modules/arc42-docs/pages/05-building-block-view.adoc`
    - [ ] `docs/modules/arc42-docs/pages/06-runtime-view.adoc`
    - [ ] `docs/modules/arc42-docs/pages/07-deployment-view.adoc`
- [ ] Update docs in config project (remove all old raspi docs and create new docs for new Pi setups)
- [ ] Make sure the image can be built for ARM
    - [ ] Can I build `linux/amd64` and `linux/arm/v6` in parallel through a matrix build? Might be faster than just specifying 2 platforms in `docker/build-push-action@v5`.  Does this make sense? This way I would also buiöd the UI bundle multiple times. Maybe rather don't do this.
    - [ ] Re-Tag `:latest` for ARM as well
- [ ] GitOps with Portainer

----
:exclamation: Re-Scoped ... simplest solution was to run the `:rc` version on localhost and control it through portainer.
